on: push

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: purcell/setup-emacs@master
        with:
          version: '30.1'

      - uses: conao3/setup-cask@master
        with:
          version: 'snapshot'

      - name: Install dependencies
        run: cask

      - name: Install dependencies for EmacSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev gcc build-essential git

      - name: Run tests
        run: cask exec buttercup -L .

      - name: Coveralls
        uses: coverallsapp/github-action@v2
