on: push

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: purcell/setup-emacs@master
        with:
          version: '28.2'

      - uses: conao3/setup-cask@master
        with:
          version: 'snapshot'

      - name: Install dependencies
        run: cask

      - name: Install dependencies for EmacSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev gcc build-essential git

      - name: Diagnose EmacSQL
        run: |
          cask exec emacs -Q --batch \
            --eval "(require 'emacsql)" \
            --eval "(message \"EmacSQL version: %s\" (if (boundp 'emacsql-version) emacsql-version \"unknown\"))" \
            --eval "(message \"Available functions: %s\" (apropos-internal \"^emacsql.*binary\\|^emacsql.*compile\" 'functionp))" \
            --eval "(require 'emacsql-sqlite)" \
            --eval "(message \"SQLite functions: %s\" (apropos-internal \"^emacsql-sqlite.*binary\\|^emacsql-sqlite.*compile\" 'functionp))"
            ---eval "(emacsql-sqlite-ensure-binary)"

      - name: Run tests
        run: cask exec buttercup -L .

      - name: Coveralls
        uses: coverallsapp/github-action@v2
